-- AlterTable
ALTER TABLE "AppConfig" ADD COLUMN IF NOT EXISTS "cafeName" TEXT;
ALTER TABLE "AppConfig" ADD COLUMN IF NOT EXISTS "cafeStreet" TEXT;
ALTER TABLE "AppConfig" ADD COLUMN IF NOT EXISTS "cafePostalCity" TEXT;
ALTER TABLE "AppConfig" ADD COLUMN IF NOT EXISTS "cafePhone" TEXT;
ALTER TABLE "AppConfig" ADD COLUMN IF NOT EXISTS "cafeEmail" TEXT;
ALTER TABLE "AppConfig" ADD COLUMN IF NOT EXISTS "cafeOwner" TEXT;
ALTER TABLE "AppConfig" ADD COLUMN IF NOT EXISTS "cafeVatId" TEXT;
ALTER TABLE "AppConfig" ADD COLUMN IF NOT EXISTS "cafeImpressumNotes" TEXT;
